apiVersion: v1
kind: Service
metadata:
  name: my-startup-nextjs-service
spec:
  selector:
    app: my-startup-nextjs
  ports:
    - protocol: TCP
      port: 80  # External port to access the app
      targetPort: 3000  # Internal container port
  type: LoadBalancer  # Expose via LoadBalancer or NodePort for local testing
