name: CI Pipeline

# Define when the pipeline should run
on:
  push:
    branches:
      - '**'  # Triggers on any push to any branch
  pull_request:
    branches:
      - main   # Triggers when a PR is opened or merged into the main branch
      - release  # Triggers when a PR is opened or merged into the release branch
    types:
      - closed  # Only trigger the pipeline when a PR is closed/merged

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build

  audit:
    name: Audit
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --production

  docker:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: audit  # Ensure audit job completes before Docker push
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: aimendoc
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t aimendoc/my-startup-nextjs:${{ github.sha }} .
      - name: Push Docker image to Docker Hub
        run: docker push aimendoc/my-startup-nextjs:${{ github.sha }}
      - name: Tag Docker image as latest
        run: |
          docker tag aimendoc/my-startup-nextjs:${{ github.sha }} aimendoc/my-startup-nextjs:latest
          docker push aimendoc/my-startup-nextjs:latest

  deploy:
    name: Deploy to Local Kubernetes Cluster
    runs-on: ubuntu-latest
    needs: docker  # Ensure the Docker job is completed before deploying
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      # Create .kube directory and set the kubeconfig file
      - name: Create .kube directory
        run: mkdir -p /home/runner/.kube  # Explicitly create the .kube directory

      # Add the kubeconfig from GitHub Secrets to the config file
      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config  # Write the KUBECONFIG secret to the kubeconfig file

      # Verify kubeconfig content and ensure it's correctly set up
      - name: Verify kubeconfig
        run: kubectl config view

      # Apply deployment and service YAML to the Kubernetes cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f H:\Git\startup-nextjs\k8s\deployment.yaml
          kubectl apply -f H:\Git\startup-nextjs\k8s\service.yaml 

      # Verify the deployment status
      - name: Verify deployment
        run: kubectl rollout status deployment/my-startup-nextjs-deployment
