name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main  # Trigger for main branch
      - release
    types:
      - closed

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build

  audit:
    name: Audit
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --production

  docker:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: audit  # Ensure audit job completes before Docker push
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: aimendoc
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t aimendoc/my-startup-nextjs:${{ github.sha }} .
      - name: Push Docker image to Docker Hub
        run: docker push aimendoc/my-startup-nextjs:${{ github.sha }}
      - name: Tag Docker image as latest
        run: |
          docker tag aimendoc/my-startup-nextjs:${{ github.sha }} aimendoc/my-startup-nextjs:latest
          docker push aimendoc/my-startup-nextjs:latest

deploy:
  name: Deploy to Local Kubernetes Cluster
  runs-on: ubuntu-latest
  needs: docker  # Ensure the Docker job is completed before deploying
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Create .kube directory and set the kubeconfig file
    - name: Create .kube directory
      run: mkdir -p /home/runner/.kube  # Ensure the directory exists

    # Set up kubeconfig using the secret
    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config  # Write the kubeconfig to the runner

    # Verify the kubeconfig is set up correctly
    - name: Verify kubeconfig
      run: kubectl config view  # This checks if the kubeconfig is valid

    # Apply the deployment and service YAML to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # Check the status of the deployment
    - name: Verify deployment
      run: kubectl rollout status deployment/my-startup-nextjs-deployment


